[[redirects]]
  from = "https://relaxed-feynman-adbdb7.netlify.com/*"
  to = "https://learnwars.com/:splat"
  force = true

[[redirects]]
  from = "https://learningwars.netlify.com/*"
  to = "https://learnwars.com/:splat"
  force = true